### ISSUE TITLE
Models created from inline object fields overwrite models created from schema definitions

### ISSUE THREAD

**Issue by cjbooms** [cjbooms/fabrikt#18]
Below, the inline object in ConnectorResource has a model named Metadata created for it, overriding the one made for the top level Metadata schema. It's not clear how to handle this situation atm, possibly an error should be thrown or some naming strategy should be developed for the models created from inline objects, such as parent_field like we do in the sql.

```
Metadata:
  type: object
  properties:
    labels:
      type: string
    annotations:
      type: string

ConnectorResource:
  type: object
  required:
    - metadata
  properties:
    metadata:
      type: object
      required:
        - name
      properties:
        name:
          type: string
```

```
data class Metadata(
    @JsonProperty("name")
    @get:NotNull
    val name: String
)
```
