### ISSUE TITLE
Support generation of array models

### ISSUE THREAD

**Issue by atollk** [cjbooms/fabrikt#188]
Currently, defining schemas as `type: array` does not correctly generate model types.

For example:
```yml
    Foo:
      type: array
      items:
        type: string
        enum:
          - X
          - Y
```

I would expect this to generate an enum type named something like `FooItem` and represent references to `Foo` as `List<FooItem>`. 

What actually happens is that references are represented as `List<Foo>` but no type `Foo` is generated.
