### ISSUE TITLE
`required` and `nullable` should be independent

### ISSUE THREAD

**Issue by atollk** [cjbooms/fabrikt#210]
I feel like this is incorrect behavior by Fabrikt but I'm not 100% sure that I'm correctly interpreting JSON schema here.

Right now, nullability, requirement, and default of schema properties is intertwined in a way that doesn't seem right to me.

Consider this schema:
```yml
components:
  schemas:
    A:
      type: object
      required:
        - e
        - f
        - g
        - h
      properties:
        nullable-false-no-default-required-false:
          type: string
          nullable: false
        nullable-true-no-default-required-false:
          type: string
          nullable: true
        nullable-false-with-default-required-false:
          type: string
          nullable: false
          default: ""
        nullable-true-with-default-required-false:
          type: string
          nullable: true
          default: ""
        nullable-false-no-default-required-true:
          type: string
          nullable: false
        nullable-true-no-default-required-true:
          type: string
          nullable: true
        nullable-false-with-default-required-true:
          type: string
          nullable: false
          default: ""
        nullable-true-with-default-required-true:
          type: string
          nullable: true
          default: ""
```

The currently generated output (with some annotations removed for readibility) is:

```kotlin
data class A(
  val nullableFalseNoDefaultRequiredFalse: String? = null,
  val nullableTrueNoDefaultRequiredFalse: String? = null,
  @get:NotNull
  val nullableFalseWithDefaultRequiredFalse: String = "",
  @get:NotNull
  val nullableTrueWithDefaultRequiredFalse: String = "",
  val nullableFalseNoDefaultRequiredTrue: String? = null,
  val nullableTrueNoDefaultRequiredTrue: String? = null,
  @get:NotNull
  val nullableFalseWithDefaultRequiredTrue: String = "",
  @get:NotNull
  val nullableTrueWithDefaultRequiredTrue: String = ""
)
```

However, I'd actually expect this:

```kotlin
data class A(
  val nullableFalseNoDefaultRequiredFalse: String? = null,
  val nullableTrueNoDefaultRequiredFalse: String? = null,
  @get:NotNull
  val nullableFalseWithDefaultRequiredFalse: String = "",
  @get:NotNull
  val nullableTrueWithDefaultRequiredFalse: String? = "",  // String? because marked as nullable
  @get:NotNull
  val nullableFalseNoDefaultRequiredTrue: String,  // String and no default because it's required
  val nullableTrueNoDefaultRequiredTrue: String?,  // No default because it's required
  @get:NotNull
  val nullableFalseWithDefaultRequiredTrue: String = "",  // Could be without default because it's required
  val nullableTrueWithDefaultRequiredTrue: String? = "" // String? because marked as nullable
)
```
