### ISSUE TITLE
Escape enum item name when it is not a valid identifier

### ISSUE THREAD

**Issue by detouched** [cjbooms/fabrikt#241]
Kotlin identifier should start with a letter or underscore.

Enum item name should be surrounded by backticks if it is not a valid Kotlin identifier.

```yaml
EnumObject:
  type: string
  enum:
    - 1one
    - 2two
```

should generate an enum with items like

```kotlin
EnumObject.`1ONE`
EnumObject.`2TWO`
```
