### ISSUE TITLE
Required but nullable object field is non-nullable in generated class 

### ISSUE THREAD

**Issue by DavidMazarro** [cjbooms/fabrikt#289]
When running a schema like this through Fabrikt:
```yaml
components:
  schemas:
    MyObject:
      type: object
      required:
        - foo
      properties:
        foo:
          type: object
          nullable: true
```
The generated class looks like this:
```kotlin
public data class MyObject(
  @param:JsonProperty("foo")
  @get:JsonProperty("foo")
  @get:NotNull
  public val foo: Map<String, Any>,
)
```
But if I'm not mistaken, one would expect:
```kotlin
public data class MyObject(
  @param:JsonProperty("foo")
  @get:JsonProperty("foo")
  @get:NotNull
  public val foo: Map<String, Any?>,
)
```

**Comment by wduncanfraser** [comment]
Seeing similar behavior with an array of nullable strings. For example:

```
        ips:
          type: array
          items:
            type: string
            nullable: true

```

Results in `List<String>` instead of `List<String?>`.
