### ISSUE TITLE
Default Value for BigDecimal is generated as an Integer

### ISSUE THREAD

**Issue by rajp33** [cjbooms/fabrikt#306]
The default value for a number type (represented as a BigDecimal should use the constructor when setting default value

Error:
` The integer literal does not conform to the expected type BigDecimal.`

Generated:
<img width="412" alt="Screenshot 2024-08-04 at 9 11 41 PM" src="https://github.com/user-attachments/assets/06831387-cea5-47de-ba03-20d643196c97">

schema:
```
markupDecimal:
    default: 0
    type: number
    multipleOf: 0.01
```
