### ISSUE TITLE
Should map values default to non-null when OAS 3.0+ is selected?

### ISSUE THREAD

**Issue by jpsugar-flow** [cjbooms/fabrikt#313]
OAS 3.0 has `nullable: true`. https://github.com/cjbooms/fabrikt/pull/276 says that there was no way to specify that map values should be nullable, but I believe this fixes it?

**Comment by cjbooms** [comment]
Would that not set Map<String, String>? rather than Map<String, String?>

**Comment by jpsugar-flow** [comment]
```yaml
type: object
additionalProperties:
    type: string
    nullable: true
```

would be `Map<String, String?>`.
