### ISSUE TITLE
uniqueItems Support - generate Set instead of List for unique items

### ISSUE THREAD

**Issue by AlexanderKomi** [cjbooms/fabrikt#387]
Hi, 

i am using fabrikt to generate an array of values, with a unique constraint.

The OpenApi Spec 3.0 includes the property "uniqueItems" to specify if an array items should be unique.

Currently fabrikt generates a Kotlin.List for the array.
It would be helpful to generate a Kotlin.Set instead, if the "uniqueItems" property is set to "true".

---

Example from the Spec:
```yaml
type: array

items:

  type: integer

uniqueItems: true
```
[1, 2, 3] – valid
[1, 1, 3] – not valid
[ ] – valid
