### ISSUE TITLE
Long enum values are line-wrapped and do not compile

### ISSUE THREAD

**Issue by dshatz** [cjbooms/fabrikt#411]
Example spec:
```
    LongEnum:
      title: LongEnum
      type: string
      enum:
        - 'value1'
        - 'long value 2 long value 2 long value 2 long value 2 long value 2 long value 2'
      x-enum-varnames:
        - VALUE1
        - LONGVALUE2_LONGVALUE2_LONGVALUE2_LONGVALUE2_LONGVALUE2_LONGVALUE2
```

Generates this code:
```kotlin
public enum class LongEnum(
  public val `value`: String,
) {
  @SerialName("value1")
  VALUE1("value1"),
  @SerialName("long value 2 long value 2 long value 2 long value 2 long value 2 long value 2")
  LONG_VALUE_2_LONG_VALUE_2_LONG_VALUE_2_LONG_VALUE_2_LONG_VALUE_2_LONG_VALUE_2("long value 2 long
      value 2 long value 2 long value 2 long value 2 long value 2"),
  ;

  public companion object {
    private val mapping: Map<String, LongEnum> = entries.associateBy(LongEnum::value)

    public fun fromValue(`value`: String): LongEnum? = mapping[value]
  }
}
```

Does not compile. Wrapping is probably enforced by kotlinpoet. Would be great if this worked.
