### ISSUE TITLE
Support String format UUID

### ISSUE THREAD

**Issue by cjbooms** [cjbooms/fabrikt#56]
A string with format type UUID should generate a data class using UUID instead of String.
```
   properties:
        stock_location_id:
          description: >
            The ID of the Stock Location from which this reservation should be fulfilled.
          type: string
          format: uuid
```
Should result in:
`val stockLocationId: UUID`
